"""
Report Generator

Formats analysis results into markdown reports using Jinja2 templates.
"""

from typing import Optional
from datetime import datetime
from pathlib import Path
import logging

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generates formatted research reports from analysis results."""

    def __init__(self, template_dir: Optional[Path] = None):
        """
        Initialize report generator.

        Args:
            template_dir: Directory containing report templates
        """
        if template_dir is None:
            template_dir = Path(__file__).parent / "templates"

        self.template_dir = template_dir
        logger.info(f"Report generator initialized with template dir: {template_dir}")

    def generate_markdown_report(
        self,
        ticker: str,
        company_name: str,
        analysis_result: dict,
        cost_usd: float = 0.0,
    ) -> str:
        """
        Generate a markdown-formatted research report.

        Args:
            ticker: Stock ticker symbol
            company_name: Full company name
            analysis_result: Dictionary containing all analysis components
            cost_usd: Cost of generating the report

        Returns:
            Markdown-formatted report string
        """
        logger.info(f"Generating report for {ticker}")

        # TODO: Implement Jinja2 template rendering
        # For now, return a placeholder template

        report = self._get_placeholder_template(
            ticker, company_name, analysis_result, cost_usd
        )

        return report

    def _get_placeholder_template(
        self, ticker: str, company_name: str, analysis_result: dict, cost_usd: float
    ) -> str:
        """Generate a placeholder report template."""

        timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

        # Extract scores (with defaults)
        business_score = analysis_result.get("business_analysis", {}).get("score", 0.0)
        moat_score = analysis_result.get("moat_analysis", {}).get("score", 0.0)
        management_score = analysis_result.get("management_analysis", {}).get(
            "score", 0.0
        )
        overall_score = analysis_result.get("recommendation", {}).get(
            "overall_score", 0.0
        )

        report = f"""# {company_name} ({ticker}) - Qualitative Analysis

**Generated:** {timestamp}  
**Analysis Cost:** ${cost_usd:.2f}

---

## Executive Summary

*This section will contain a concise summary of the qualitative analysis.*

---

## Business Model Analysis

### What Does the Company Do?

*Business description will appear here.*

### Revenue Streams

*Revenue stream analysis will appear here.*

### Key Products/Services

*Key products and services will appear here.*

**Business Model Score:** {business_score:.1f}/10

---

## Competitive Moat Assessment

### Competitive Advantages

*Competitive advantages analysis will appear here.*

### Moat Strength

**Moat Score:** {moat_score:.1f}/10

*Moat strength explanation will appear here.*

### Threats to Moat

*Moat threats will appear here.*

---

## Management Quality

### Leadership Team

*Leadership assessment will appear here.*

### Capital Allocation Track Record

*Capital allocation analysis will appear here.*

**Management Score:** {management_score:.1f}/10

---

## Risk Factors

### Business Risks

*Business risks will appear here.*

### Financial Risks

*Financial risks will appear here.*

### Regulatory/Legal Risks

*Regulatory risks will appear here.*

---

## Investment Recommendation

**Qualitative Score:** {overall_score:.1f}/10

*Investment recommendation will appear here.*

### Alignment with Rule #1 Criteria

- **Meaning:** *Assessment pending*
- **Moat:** *Assessment pending*
- **Management:** *Assessment pending*
- **Margin of Safety:** *Assessment pending*

---

## Sources

- SEC 10-K Filing (Most Recent)
- SEC 10-Q Filings (Last 4 quarters)
- Company Website & Investor Relations
- Financial Metrics from Common Investor Platform

---

**Disclaimer:** This report is generated by an AI system for informational purposes only. 
It does not constitute investment advice. Always verify information with primary sources 
and consult a financial advisor before making investment decisions.
"""

        return report

    def save_report(
        self, report_content: str, ticker: str, output_path: Optional[Path] = None
    ) -> Path:
        """
        Save report to file.

        Args:
            report_content: Markdown report content
            ticker: Stock ticker symbol
            output_path: Optional custom output path

        Returns:
            Path to saved report file
        """
        if output_path is None:
            timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
            filename = f"{ticker}_qualitative_report_{timestamp}.md"
            output_path = Path("/tmp") / filename

        output_path.write_text(report_content)
        logger.info(f"Report saved to: {output_path}")

        return output_path


# Convenience function
def generate_report(ticker: str, company_name: str, analysis_result: dict) -> str:
    """
    Convenience function to generate a report.

    Args:
        ticker: Stock ticker symbol
        company_name: Full company name
        analysis_result: Analysis result dictionary

    Returns:
        Markdown-formatted report
    """
    generator = ReportGenerator()
    return generator.generate_markdown_report(ticker, company_name, analysis_result)
